Add documentation for ACF options pages
flyntwp/flynt-docs pull request #65
Opened 2017-06-29 15:11 UTC by emcarru

First take on documenting options pages. Unsure on how to cover everything best here. Maybe we can talk through it if you have some time! 

resolves #21

2017-07-25 15:29 UTC, dgrdl requested changes
Makes sense to me, listed some small issues in the comments below.

2017-07-25 15:29 UTC, Qakulukiam commented on content/guide/configuration/options-pages.md
> +[Advanced Custom Fields Options pages](https://www.advancedcustomfields.com/add-ons/options-page/) provide a way to create new, extra admin pages in the sidebar of the WordPress back end.
Spelling: Options Pages? Option Pages? option pages?

2017-07-25 15:29 UTC, Qakulukiam commented on content/guide/configuration/options-pages.md
> +**Global Options:** This options page is for fields that should keep the same value in all languages. If your theme uses the WordPress plugin [WPML](https://wpml.org/), any field defined as a **globa
or or or or or or

2017-07-25 15:29 UTC, Qakulukiam commented on content/guide/configuration/options-pages.md
> +To show fields from a component or feature on either of the options pages, the fields must be defined in `fields.json` inside an array with the name of the options page.
Custom Post Types can also have options pages

2017-07-25 15:29 UTC, Qakulukiam commented on content/guide/configuration/options-pages.md
> +      "append": "",
Prepend, append unnecessary. I know you probably just copy pasted, but still.

2017-07-25 15:29 UTC, Qakulukiam commented on content/guide/configuration/options-pages.md
> +If these fields are defined inside a feature or post type, or you need to use options of one component inside of another, it is necessary to use the `OptionPages` class provided by the [Acf](https://
*custom* post type

2017-07-25 15:29 UTC, Qakulukiam commented on content/guide/configuration/options-pages.md
> +If these fields are defined inside a feature or post type, or you need to use options of one component inside of another, it is necessary to use the `OptionPages` class provided by the [Acf](https://
Acf link kind of strange, should probably be on "Acf feature" instead so it doesn't look like a link to the ACF website.

2017-07-25 15:29 UTC, Qakulukiam commented on content/guide/configuration/options-pages.md
> +If these fields are defined inside a feature or post type, or you need to use options of one component inside of another, it is necessary to use the `OptionPages` class provided by the [Acf](https://
maybe mention "static `get` function"?

2017-07-25 15:29 UTC, Qakulukiam commented on content/guide/configuration/options-pages.md
> +$GoogleAnalyticsId = OptionPages::get('globalOptions', 'feature', 'GoogleAnalytics', 'gaID');
I always wonder if people might be confused by mixed upper and lowercase values like here. It works either way, but it's not really obvious...

2017-07-25 15:29 UTC, Qakulukiam commented on content/guide/configuration/options-pages.md
> +$GoogleAnalyticsId = OptionPages::get('globalOptions', 'feature', 'GoogleAnalytics', 'gaID');
Also, not sure about this, but you mention the `gaId` option above and here it looks for the `gaID` option. Note the D. ;)

2017-07-25 15:29 UTC, Qakulukiam commented on content/guide/configuration/options-pages.md
> +To show fields under the **translatable options** page, register the fields inside the `translatableOptions` array:
should "translatable options" and "global options" above be title case? As in the listing before?

2017-07-25 15:29 UTC, Qakulukiam commented on content/guide/configuration/options-pages.md
> +```
No closing remarks? Just ends with an example, might be weird?

2017-08-04 14:43 UTC, emcarru commented on content/guide/configuration/options-pages.md
> +```
I don't think it needs closing remarks since it's "plain" documentation rather than a tutorial. I can't really think of anything suitable anyway!

2017-08-04 15:13 UTC, dgrdl approved these changes

2017-08-04 16:23 UTC, merged